# Generated by Django 3.0 on 2021-06-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210601_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time created'),
        ),
    ]
