# Generated by Django 3.0 on 2021-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210601_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_created',
            field=models.DateTimeField(verbose_name='time created'),
        ),
    ]
