# Generated by Django 3.0 on 2021-06-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210601_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_created',
            field=models.DateTimeField(auto_now=True, verbose_name='time created'),
        ),
    ]
