# Generated by Django 3.0 on 2021-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210603_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_answer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='timestamp'),
        ),
    ]
